#!/bin/zsh

curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.17.1/cloud-sql-proxy.darwin.amd64
chmod +x cloud-sql-proxy
sudo mv cloud-sql-proxy /usr/local/bin

echo "Downloaded cloud-sql-proxy to /usr/local/bin/cloud-sql-proxy"
